Policy-based governance, risk, and compliance paper
kubernetes/sig-security pull request #94
Opened 2023-07-09 18:49 UTC by JimBugwadia

Fixes https://github.com/kubernetes/sig-security/issues/93

2023-07-09 18:51 UTC, JimBugwadia commented
Preview at: https://github.com/kubernetes/sig-security/blob/21c33081ff5118ab5afefb65c15af29a34c10356/sig-security-docs/papers/policy_grc/kubernetes-grc.md.

2023-07-10 17:49 UTC, JonZeolla requested changes
It seems like not all of the authors were moved over from the g doc; unsure if that was intentional

2023-07-10 17:49 UTC, JonZeolla commented on sig-security-docs/papers/policy_grc/kubernetes-grc.md
> +* Robert Ficcaglia, Sunstone Secure
```suggestion
* Robert Ficcaglia, Sunstone Secure
* Poonam Lamba, ?
* Yuji Watanabe, ?
* Brandt Keller, ?
* Jon Zeolla, Seiso
```

2023-07-11 08:43 UTC, viccuad commented on sig-security-docs/papers/policy_grc/kubernetes-grc.md
> +* [KubeWarden](https://www.kubewarden.io/): Kubewarden is a policy engine for Kubernetes. It helps with keeping your Kubernetes clusters secure and compliant.
```suggestion
* [Kubewarden](https://kubewarden.io/): Kubewarden is a policy engine for Kubernetes with validation, mutation, image verification, and context-aware policies. It aims to be the universal policy engine as its policies are Wasm modules, allowing to use the language of your choice.
```

2023-07-11 08:43 UTC, viccuad commented on sig-security-docs/papers/policy_grc/kubernetes-grc.md
> +* [Tetragon]() : Cilium’s new Tetragon component enables powerful real time, eBPF-based Security Observability and Runtime Enforcement.
```suggestion
* [Tetragon](https://github.com/cilium/tetragon) : Cilium’s new Tetragon component enables powerful real time, eBPF-based Security Observability and Runtime Enforcement.
```

2023-07-11 08:43 UTC, viccuad commented on sig-security-docs/papers/policy_grc/kubernetes-grc.md
> +* [Tracee]() : Tracee uses eBPF technology to tap into your system and give you access to hundreds of events that help you understand how your system behaves.
```suggestion
* [Tracee](https://github.com/aquasecurity/tracee) : Tracee uses eBPF technology to tap into your system and give you access to hundreds of events that help you understand how your system behaves.
```

2023-07-11 08:43 UTC, viccuad commented on sig-security-docs/papers/policy_grc/kubernetes-grc.md
> +* [Kubescape](https://github.com/kubescape/kubescape) : Kubescape is an open-source Kubernetes security platform. It includes risk analysis, security compliance, and misconfiguration scanning
```suggestion
* [Kubescape](https://github.com/kubescape/kubescape) : Kubescape is an open-source Kubernetes security platform. It includes risk analysis, security compliance, and misconfiguration scanning.
```

2023-07-11 08:43 UTC, viccuad commented on sig-security-docs/papers/policy_grc/kubernetes-grc.md
> +* [Open Cluster Management](https://open-cluster-management.io/) : Provides a multi-cluster management technology that can be used  to manage multiple clusters for creating/importing clusters, config
```suggestion
* [Open Cluster Management](https://open-cluster-management.io/) : Provides a multi-cluster management technology that can be used  to manage multiple clusters for creating/importing clusters, configure them to desired state using policies.
```

2023-07-11 08:46 UTC, viccuad reviewed
Hi folks, this is indeed a nice paper :). Added some silly nits, and since I'm a Kubewarden maintainer, reworded its summary too.

2023-07-17 14:36 UTC, JimBugwadia commented on sig-security-docs/papers/policy_grc/kubernetes-grc.md
> +* Robert Ficcaglia, Sunstone Secure
Thanks, updated.

2023-07-17 14:56 UTC, viccuad approved these changes
Thanks for the fixes, LGTM!

2023-07-19 15:18 UTC, jrnp7 commented
LGTM

2023-08-02 15:42 UTC, JonZeolla commented
LGTM 🚀

2023-08-10 14:37 UTC, savitharaghunathan approved these changes
/approve

2023-08-10 14:38 UTC, savitharaghunathan commented
/lgtm

2023-08-10 14:39 UTC, merged